-- Cria schemas/tabelas simples
CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200),
  email VARCHAR2(200) UNIQUE,
  timezone VARCHAR2(50),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE user_answers (
  answer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER,
  question_code VARCHAR2(100),
  answer_text CLOB,
  answer_value VARCHAR2(200),
  answered_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE user_profile (
  profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER,
  computed_json CLOB,
  recommended_career VARCHAR2(200),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE study_plan (
  plan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER,
  career_code VARCHAR2(100),
  plan_json CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
